site_name: MabelisYT's Personal Blog
nav:
  - Home: index.md
  - "Programming Blog":
    - Programming/index.md
    - "MabelMedia-LLC.SharpPlusNative":
      - MabelMedia-LLC.SharpPlusNative: Programming/SharpPlusNative/index.md
      - "UI ToolKit Update 25/05/2025": Programming/SharpPlusNative/25-05-2025.md
theme:
  favicon: assets/images/favicon.png
  name: material
  language: en
  logo: assets/images/favicon.png
  palette:
    - scheme: default
      primary: pink
      accent: red
      toggle:
        icon: material/brightness-3
        name: Switch To Dark Mode
    - scheme: slate
      primary: pink
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch To Light Mode
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
extra_css:
  - assets/css/extra.css
site_url: https://www.mabelisyt.co
site_author: MabelMedia LLC
copyright: Copyright &copy; MabelMedia LLC. All Rights Reserved.
extra:
  generator: false
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 


      emoji_generator: !!python/name:material.extensions.emoji.to_svg